"""add all models

Revision ID: da4eb41a29fa
Revises: 132ee07ae9c5
Create Date: 2025-10-26 04:04:34.376543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da4eb41a29fa'
down_revision: Union[str, None] = '132ee07ae9c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('donor_name', sa.String(length=255), nullable=False),
    sa.Column('donor_email', sa.String(length=255), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', name='donationstatus'), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('people_impacted', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_donations_org_id'), 'donations', ['org_id'], unique=False)
    op.create_table('chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chats_session_id'), 'chats', ['session_id'], unique=True)
    op.create_index(op.f('ix_chats_user_id'), 'chats', ['user_id'], unique=False)
    op.create_table('donation_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('donation_id', sa.Integer(), nullable=False),
    sa.Column('entry_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ledger_metadata', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['donation_id'], ['donations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_donation_ledger_donation_id'), 'donation_ledger', ['donation_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('message_metadata', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_chat_id'), 'chat_messages', ['chat_id'], unique=False)
    op.add_column('articles', sa.Column('link_doc', sa.String(length=500), nullable=True))
    op.add_column('articles', sa.Column('link_image', sa.String(length=500), nullable=True))
    op.add_column('articles', sa.Column('version', sa.Integer(), nullable=False))
    op.add_column('articles', sa.Column('author_id', sa.Integer(), nullable=True))
    op.add_column('articles', sa.Column('approved_by_id', sa.Integer(), nullable=True))
    op.add_column('articles', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('articles', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('articles', sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('articles', 'body_md',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.create_index(op.f('ix_articles_slug'), 'articles', ['slug'], unique=True)
    op.create_foreign_key(None, 'articles', 'users', ['author_id'], ['id'])
    op.create_foreign_key(None, 'articles', 'users', ['approved_by_id'], ['id'])
    op.add_column('orgs', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('orgs', sa.Column('approved', sa.Boolean(), nullable=False))
    op.add_column('orgs', sa.Column('approved_by_id', sa.Integer(), nullable=True))
    op.add_column('orgs', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('orgs', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('orgs', sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orgs', sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_orgs_email'), 'orgs', ['email'], unique=True)
    op.create_index(op.f('ix_orgs_invite_code'), 'orgs', ['invite_code'], unique=True)
    op.add_column('users', sa.Column('assistente_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('org_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_users_cpf'), 'users', ['cpf'], unique=True)
    op.create_foreign_key(None, 'users', 'users', ['assistente_id'], ['id'])
    op.create_foreign_key(None, 'users', 'orgs', ['org_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_cpf'), table_name='users')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'org_id')
    op.drop_column('users', 'assistente_id')
    op.drop_index(op.f('ix_orgs_invite_code'), table_name='orgs')
    op.drop_index(op.f('ix_orgs_email'), table_name='orgs')
    op.drop_column('orgs', 'approved_at')
    op.drop_column('orgs', 'verified_at')
    op.drop_column('orgs', 'updated_at')
    op.drop_column('orgs', 'created_at')
    op.drop_column('orgs', 'approved_by_id')
    op.drop_column('orgs', 'approved')
    op.drop_column('orgs', 'description')
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.drop_index(op.f('ix_articles_slug'), table_name='articles')
    op.alter_column('articles', 'body_md',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('articles', 'approved_at')
    op.drop_column('articles', 'updated_at')
    op.drop_column('articles', 'created_at')
    op.drop_column('articles', 'approved_by_id')
    op.drop_column('articles', 'author_id')
    op.drop_column('articles', 'version')
    op.drop_column('articles', 'link_image')
    op.drop_column('articles', 'link_doc')
    op.drop_index(op.f('ix_chat_messages_chat_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_donation_ledger_donation_id'), table_name='donation_ledger')
    op.drop_table('donation_ledger')
    op.drop_index(op.f('ix_chats_user_id'), table_name='chats')
    op.drop_index(op.f('ix_chats_session_id'), table_name='chats')
    op.drop_table('chats')
    op.drop_index(op.f('ix_donations_org_id'), table_name='donations')
    op.drop_table('donations')
    # ### end Alembic commands ###
